### PR TITLE
Add rostemplate

### PR DESCRIPTION
**Pull request by dieghernan**
See #17

### CODE REVIEW

**Comment by jlopezper** [comment]
Thank you very much for this PR @dieghernan. We'll remove the Travis and AppVeyor builds asap (probably this week).

**Comment by dieghernan** [comment]
Thanks, regarding the checks feel free to use the CI you prefer, as you are the owner of the project (you can use all at the same time if you wish😱) . The key is to implement cron in your desired CI.

Regards

**Comment by jlopezper** [comment]
We were already thinking about migrating the checks from Travis and AppVeyor to GH Actions, so this PR is more than welcome. Thanks again.

**Comment by dieghernan** [comment]
A small piece of advice. If you consider moving away from Travis you would need to add an action to run codecov. Have a look to https://github.com/rOpenSpain/mapSpain/blob/master/.github/workflows/test-coverage.yaml

That would provides a smooth migration to gh-actions.

**Pull request merged**
